apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-logging-config
  namespace: dev
data:
  access.conf: |
    server {
      listen 80;
      server_name localhost;

      access_log /dev/stdout;
      error_log /dev/stderr;

      location / {
        return 200 'Hello from NGINX\n';
      }
    }
